#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPeluqueria
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BDpeluqueria")]
	public partial class ModeloHorarioDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertDisponibilidadH(DisponibilidadH instance);
    partial void UpdateDisponibilidadH(DisponibilidadH instance);
    partial void DeleteDisponibilidadH(DisponibilidadH instance);
        #endregion
        public ModeloHorarioDataContext() :
         base(global::System.Configuration.ConfigurationManager.ConnectionStrings["BDpeluqueriaConnectionString"].ConnectionString, mappingSource)
        {
            OnCreated();
        }
        public ModeloHorarioDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModeloHorarioDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModeloHorarioDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModeloHorarioDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DisponibilidadH> DisponibilidadH
		{
			get
			{
				return this.GetTable<DisponibilidadH>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.buscarHorario")]
		public ISingleResult<buscarHorarioResult> buscarHorario([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> cedulaP)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cedulaP);
			return ((ISingleResult<buscarHorarioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertarHorarioP")]
		public int insertarHorarioP([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idDisponibilidad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idHorario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HorainicioCorte", DbType="Int")] System.Nullable<int> horainicioCorte, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HoraFinCorte", DbType="Int")] System.Nullable<int> horaFinCorte, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> cedulaP, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string estado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idDisponibilidad, idHorario, horainicioCorte, horaFinCorte, cedulaP, estado);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.actualizarEstado")]
		public int actualizarEstado([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estado", DbType="VarChar(50)")] string estado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdDisponibilidad", DbType="Int")] System.Nullable<int> idDisponibilidad)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), estado, idDisponibilidad);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DisponibilidadH")]
	public partial class DisponibilidadH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdDisponibilidad;
		
		private int _idHorario;
		
		private System.Nullable<int> _HorainicioCorte;
		
		private System.Nullable<int> _HoraFinCorte;
		
		private int _cedulaP;
		
		private string _estado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdDisponibilidadChanging(int value);
    partial void OnIdDisponibilidadChanged();
    partial void OnidHorarioChanging(int value);
    partial void OnidHorarioChanged();
    partial void OnHorainicioCorteChanging(System.Nullable<int> value);
    partial void OnHorainicioCorteChanged();
    partial void OnHoraFinCorteChanging(System.Nullable<int> value);
    partial void OnHoraFinCorteChanged();
    partial void OncedulaPChanging(int value);
    partial void OncedulaPChanged();
    partial void OnestadoChanging(string value);
    partial void OnestadoChanged();
    #endregion
		
		public DisponibilidadH()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdDisponibilidad", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdDisponibilidad
		{
			get
			{
				return this._IdDisponibilidad;
			}
			set
			{
				if ((this._IdDisponibilidad != value))
				{
					this.OnIdDisponibilidadChanging(value);
					this.SendPropertyChanging();
					this._IdDisponibilidad = value;
					this.SendPropertyChanged("IdDisponibilidad");
					this.OnIdDisponibilidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idHorario", DbType="Int NOT NULL")]
		public int idHorario
		{
			get
			{
				return this._idHorario;
			}
			set
			{
				if ((this._idHorario != value))
				{
					this.OnidHorarioChanging(value);
					this.SendPropertyChanging();
					this._idHorario = value;
					this.SendPropertyChanged("idHorario");
					this.OnidHorarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HorainicioCorte", DbType="Int")]
		public System.Nullable<int> HorainicioCorte
		{
			get
			{
				return this._HorainicioCorte;
			}
			set
			{
				if ((this._HorainicioCorte != value))
				{
					this.OnHorainicioCorteChanging(value);
					this.SendPropertyChanging();
					this._HorainicioCorte = value;
					this.SendPropertyChanged("HorainicioCorte");
					this.OnHorainicioCorteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoraFinCorte", DbType="Int")]
		public System.Nullable<int> HoraFinCorte
		{
			get
			{
				return this._HoraFinCorte;
			}
			set
			{
				if ((this._HoraFinCorte != value))
				{
					this.OnHoraFinCorteChanging(value);
					this.SendPropertyChanging();
					this._HoraFinCorte = value;
					this.SendPropertyChanged("HoraFinCorte");
					this.OnHoraFinCorteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cedulaP", DbType="Int NOT NULL")]
		public int cedulaP
		{
			get
			{
				return this._cedulaP;
			}
			set
			{
				if ((this._cedulaP != value))
				{
					this.OncedulaPChanging(value);
					this.SendPropertyChanging();
					this._cedulaP = value;
					this.SendPropertyChanged("cedulaP");
					this.OncedulaPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="VarChar(50)")]
		public string estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class buscarHorarioResult
	{
		
		private int _IdDisponibilidad;
		
		private int _idHorario;
		
		private System.Nullable<int> _HorainicioCorte;
		
		private System.Nullable<int> _HoraFinCorte;
		
		private int _cedulaP;
		
		private string _estado;
		
		public buscarHorarioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdDisponibilidad", DbType="Int NOT NULL")]
		public int IdDisponibilidad
		{
			get
			{
				return this._IdDisponibilidad;
			}
			set
			{
				if ((this._IdDisponibilidad != value))
				{
					this._IdDisponibilidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idHorario", DbType="Int NOT NULL")]
		public int idHorario
		{
			get
			{
				return this._idHorario;
			}
			set
			{
				if ((this._idHorario != value))
				{
					this._idHorario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HorainicioCorte", DbType="Int")]
		public System.Nullable<int> HorainicioCorte
		{
			get
			{
				return this._HorainicioCorte;
			}
			set
			{
				if ((this._HorainicioCorte != value))
				{
					this._HorainicioCorte = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoraFinCorte", DbType="Int")]
		public System.Nullable<int> HoraFinCorte
		{
			get
			{
				return this._HoraFinCorte;
			}
			set
			{
				if ((this._HoraFinCorte != value))
				{
					this._HoraFinCorte = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cedulaP", DbType="Int NOT NULL")]
		public int cedulaP
		{
			get
			{
				return this._cedulaP;
			}
			set
			{
				if ((this._cedulaP != value))
				{
					this._cedulaP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="VarChar(50)")]
		public string estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this._estado = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
