#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPeluqueria
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BDpeluqueria")]
	public partial class ModeloCiDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertCitas(Citas instance);
    partial void UpdateCitas(Citas instance);
    partial void DeleteCitas(Citas instance);
        #endregion
        public ModeloCiDataContext() :
         base(global::System.Configuration.ConfigurationManager.ConnectionStrings["BDpeluqueriaConnectionString"].ConnectionString, mappingSource)
        {
            OnCreated();
        }

        public ModeloCiDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModeloCiDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModeloCiDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModeloCiDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Citas> Citas
		{
			get
			{
				return this.GetTable<Citas>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.buscarCita")]
		public ISingleResult<buscarCitaResult> buscarCita([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> cedulac)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cedulac);
			return ((ISingleResult<buscarCitaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.eliminarCitas")]
		public int eliminarCitas([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idCita)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCita);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertarCitas")]
		public int insertarCitas([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idCita, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string cedulac, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string cedulaP, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string idDisponibilidad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string idCorte)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCita, cedulac, cedulaP, idDisponibilidad, idCorte);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.buscarCorte")]
		public ISingleResult<buscarCorteResult> buscarCorte([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCorte", DbType="Int")] System.Nullable<int> idCorte)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCorte);
			return ((ISingleResult<buscarCorteResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Citas")]
	public partial class Citas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdCita;
		
		private System.Nullable<int> _cedulac;
		
		private System.Nullable<int> _cedulaP;
		
		private System.Nullable<int> _idDisponibilidad;
		
		private System.Nullable<int> _idCorte;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdCitaChanging(int value);
    partial void OnIdCitaChanged();
    partial void OncedulacChanging(System.Nullable<int> value);
    partial void OncedulacChanged();
    partial void OncedulaPChanging(System.Nullable<int> value);
    partial void OncedulaPChanged();
    partial void OnidDisponibilidadChanging(System.Nullable<int> value);
    partial void OnidDisponibilidadChanged();
    partial void OnidCorteChanging(System.Nullable<int> value);
    partial void OnidCorteChanged();
    #endregion
		
		public Citas()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCita", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdCita
		{
			get
			{
				return this._IdCita;
			}
			set
			{
				if ((this._IdCita != value))
				{
					this.OnIdCitaChanging(value);
					this.SendPropertyChanging();
					this._IdCita = value;
					this.SendPropertyChanged("IdCita");
					this.OnIdCitaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cedulac", DbType="Int")]
		public System.Nullable<int> cedulac
		{
			get
			{
				return this._cedulac;
			}
			set
			{
				if ((this._cedulac != value))
				{
					this.OncedulacChanging(value);
					this.SendPropertyChanging();
					this._cedulac = value;
					this.SendPropertyChanged("cedulac");
					this.OncedulacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cedulaP", DbType="Int")]
		public System.Nullable<int> cedulaP
		{
			get
			{
				return this._cedulaP;
			}
			set
			{
				if ((this._cedulaP != value))
				{
					this.OncedulaPChanging(value);
					this.SendPropertyChanging();
					this._cedulaP = value;
					this.SendPropertyChanged("cedulaP");
					this.OncedulaPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDisponibilidad", DbType="Int")]
		public System.Nullable<int> idDisponibilidad
		{
			get
			{
				return this._idDisponibilidad;
			}
			set
			{
				if ((this._idDisponibilidad != value))
				{
					this.OnidDisponibilidadChanging(value);
					this.SendPropertyChanging();
					this._idDisponibilidad = value;
					this.SendPropertyChanged("idDisponibilidad");
					this.OnidDisponibilidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCorte", DbType="Int")]
		public System.Nullable<int> idCorte
		{
			get
			{
				return this._idCorte;
			}
			set
			{
				if ((this._idCorte != value))
				{
					this.OnidCorteChanging(value);
					this.SendPropertyChanging();
					this._idCorte = value;
					this.SendPropertyChanged("idCorte");
					this.OnidCorteChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class buscarCitaResult
	{
		
		private int _IdCita;
		
		private System.Nullable<int> _cedulac;
		
		private System.Nullable<int> _cedulaP;
		
		private System.Nullable<int> _idDisponibilidad;
		
		private System.Nullable<int> _idCorte;
		
		public buscarCitaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCita", DbType="Int NOT NULL")]
		public int IdCita
		{
			get
			{
				return this._IdCita;
			}
			set
			{
				if ((this._IdCita != value))
				{
					this._IdCita = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cedulac", DbType="Int")]
		public System.Nullable<int> cedulac
		{
			get
			{
				return this._cedulac;
			}
			set
			{
				if ((this._cedulac != value))
				{
					this._cedulac = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cedulaP", DbType="Int")]
		public System.Nullable<int> cedulaP
		{
			get
			{
				return this._cedulaP;
			}
			set
			{
				if ((this._cedulaP != value))
				{
					this._cedulaP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDisponibilidad", DbType="Int")]
		public System.Nullable<int> idDisponibilidad
		{
			get
			{
				return this._idDisponibilidad;
			}
			set
			{
				if ((this._idDisponibilidad != value))
				{
					this._idDisponibilidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCorte", DbType="Int")]
		public System.Nullable<int> idCorte
		{
			get
			{
				return this._idCorte;
			}
			set
			{
				if ((this._idCorte != value))
				{
					this._idCorte = value;
				}
			}
		}
	}
	
	
}
#pragma warning restore 1591
